version: '2'

services:

  filebeat:
    build: ./
    hostname: filebeat
    container_name: filebeat
    volumes:
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /opt/logs:/opt/logs
