apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      type: maven
