apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-registry-config
data:
  config: |
    version: 0.1
    log:
      level: debug
      fields:
        service: registry
    storage:
      filesystem:
        rootdirectory: /storage
      cache:
        layerinfo: inmemory
      maintenance:
        uploadpurging:
          enabled: false
      delete:
        enabled: true
    http:
      addr: :5000
      secret: placeholder
      debug:
        addr: localhost:5001
    auth:
      token:
        issuer: harbor-token-issuer
        realm: http://172.31.21.226/service/token
        rootcertbundle: /etc/docker/registry/root.crt
        service: harbor-registry
    notifications:
      endpoints:
        - name: harbor
          disabled: false
          url: http://ui/service/notifications
          timeout: 3000ms
          threshold: 5
          backoff: 1s

  cert: |
    -----BEGIN CERTIFICATE-----
    MIIE0zCCArugAwIBAgIJAPj7TVyQnr2wMA0GCSqGSIb3DQEBCwUAMAAwHhcNMTcx
    MjAxMDc1MDM0WhcNMjcxMTI5MDc1MDM0WjAAMIICIjANBgkqhkiG9w0BAQEFAAOC
    Ag8AMIICCgKCAgEAwm2URImjsDpAcMH70DJd05oujR+hLBwsMoAGQel2OOdT8AEg
    YYqVdhu+DXVl1ApM6TlupLKDU9IRisQI8eiEJGgBQobF3VWOl8bJMaOTzgyAcpN4
    pMuXsNgdtLPYUVkHna3tUR8hlOVvY/eFUs7awk77H4pZ4VvkhFyOHK98UqUYInVa
    nFJnLd4g2x2ie0zr7Q32kHSdjTwhHyDvIYCD4crEeCqxbYA3zvEuSuQ5/S4Njb1u
    k2wOeslNLyvmMZ0QtLO064Aoc0srr8bd7NeGct811i698p2nREqI+wXIOz17OiXB
    ieXsh/i3t7nF586Ljeikc0g0MOFFdSKKxKF3CbB2MDad/ngf+lTc/67ODBQwO9Zv
    gQt6EIyPukbUl5G8f0C3TQcfSDD2BoJJOdRpdVxowK6kUnuGCaoX99IIEhMtj6iE
    +iIklOOi1PRAoAfDxfmW/ffCBld/adCP99uYYrAP9LgHCu6OV5ZwihT0cZzZ2645
    wvKFLnF75DACCXWWI+CkgnIUIaN0ZSZM22BsK0FkY/gIWcIiUmU8cu0M2Z/cg4sx
    3A+1q0KE3C57loISen1a/w41JtYHhecbeIZTOBq1PvSj4MKLET6PbDWhh0FWx2RZ
    hYuJWXrGL+fAtzOW+7/rqtLSgfc5LyP9XhafuNfppT+qAeUn/B5cdeMM4jsCAwEA
    AaNQME4wHQYDVR0OBBYEFOkXA9UQ2N1rIU23eF6W2YGWPpUOMB8GA1UdIwQYMBaA
    FOkXA9UQ2N1rIU23eF6W2YGWPpUOMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEL
    BQADggIBAAgGPobnUEwOTM87k2uXT3gfRb/OtCLe1Jf/KJ1JvDzV4Qs9jSzBro+s
    SoFMFur2mkIW2XD8VtUuiKin4m1ETOmmmHPqOUiAyaRruMUsGYWpOekSPvP4ncnz
    fNKY0T3F60Aw2O1fP/4ilmhd/Onzu5kG5rLJeIkxwnAemVj/ge32aoSmtJMDSWMj
    vDnvNnADolNSgoV/PBmnZex92dl09DIqfwlvdg8e1FUVevfVwRhQdVKOx74EjLLP
    AF+qSBKC2tKsMFtfd9uuB8f8BI8W5H38/7qYsuEM3w4sRC5xoNwhtW2UFbnMne1r
    zOeLxAYbstApWhgJSe1AXmEITOj/JEwr/febO9csfDeHeRaw9hs46Y7uRJPoyoTl
    c0czb5hyJUVmVe/0+Ogmuiz3NkkupyW2WkwnSu8eg6fzt+xO5BCunCQmZzU4bycA
    BEpzVaLeHNydfP8VYCq2dvtL/PyveUgcp/jIBLsAm8MRU+qg/rg6I717MFYvyrOj
    7SQuFXAZbhAQ9+5b3dOPF7DONAXzqAHAd+fMpAf4+87sZkHs9+pL/zgVHIMxjCpK
    Qs7ztUzg2aiAHD1YzsodnFfTNSkOpfjS5a8hrxY8954sij/Ys9tdxvQmNUUUeMH+
    AEQKyWl9zDbos4J67c6dNB9UBXSFuWOX6ITTZ5DHJSQsV/PTGas1
    -----END CERTIFICATE-----
    

