apiVersion: v1
kind: PersistentVolume
metadata:
  name: maven-pv
  labels:
    type: maven
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/maven

  #   - ReadWriteMany
  # glusterfs:
  #   endpoints: "glusterfs-cluster"
  #   path: "k8s-volume"
  #   readOnly: false
