apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-ui
spec:
  rules:
  - host: jenkins.idealsoftone.com
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins-ui
          servicePort: 8080
