apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-ui-config
data:
  CONFIG_PATH: /etc/ui/app.conf
  LOG_LEVEL: debug
  UI_SECRET: "{{ui_secret}}"
  JOBSERVICE_SECRET: "{{jobservice_secret}}"
  GODEBUG: netdns=cgo
  SECRET_KEY: "{{secret_key}}"
  config: |
    appname = registry
    runmode = dev
    [lang]
    types = en-US|zh-CN
    names = en-US|zh-CN
    [dev]
    httpport = 80
    [mail]
    host = {{email_server}}
    port = {{email_server_port}}
    username = {{email_username}}
    password = {{email_password}}
    from = {{email_from}}
    ssl = {{email_ssl}}
  pkey: |
    {{4 auth_pkey}}


