version: '2'

services:
  eureka:
    image: batizhao/openjdk:8
    hostname: discovery
    container_name: discovery
    command: java -jar /opt/poseidon-discovery-0.0.1-SNAPSHOT.jar
    restart: always
    volumes:
      - /opt/web/poseidon/discovery:/opt
    expose:
      - "8761"
    ports:
      - "8761:8761"
    environment:
      TZ: Asia/Shanghai
    networks:
      - poseidon

  zuul:
    image: batizhao/openjdk:8
    hostname: gateway
    container_name: gateway
    command: java -jar /opt/poseidon-gateway-0.0.1-SNAPSHOT.jar
    restart: always
    volumes:
      - /opt/web/poseidon/gateway:/opt
    expose:
      - "8050"
    ports:
      - "8050:8050"
    environment:
      TZ: Asia/Shanghai
    networks:
      - poseidon
    depends_on:
      - eureka

  uaa:
    image: batizhao/openjdk:8
    hostname: uaa
    container_name: uaa
    command: java -jar /opt/poseidon-uaa-0.0.1-SNAPSHOT.jar
    restart: always
    volumes:
      - /opt/web/poseidon/uaa:/opt
    expose:
      - "8002"
    ports:
      - "8002:8002"
    environment:
      TZ: Asia/Shanghai
    networks:
      - poseidon
    depends_on:
      - eureka

networks:
  poseidon:
    external: true
