version: '2'

services:
  user:
    image: batizhao/java:8
    hostname: user
    container_name: user
    command: java -Dfile.encoding=utf-8 -jar /opt/amphitrite-user-0.0.1-SNAPSHOT.jar
    volumes:
      - /Users/batizhao/Documents/oschina/amphitrite/amphitrite-user/target/:/opt
    expose:
      - "8001"
    ports:
      - "8001:8001"
    environment:
      TZ: Asia/Shanghai
    networks:
      - poseidon

networks:
  poseidon:
    external: true
