version: '2'

services:
  engine:
    image: batizhao/openjdk:8
    hostname: engine
    container_name: engine
    command: java -Dfile.encoding=utf-8 -jar /opt/amphitrite-engine-0.0.1-SNAPSHOT.jar
    volumes:
      - /opt/web/amphitrite/engine:/opt
    expose:
      - "8000"
    ports:
      - "8000:8000"
    environment:
      TZ: Asia/Shanghai
    networks:
      - poseidon

  user:
    image: batizhao/openjdk:8
    hostname: user
    container_name: user
    command: java -Dfile.encoding=utf-8 -jar /opt/amphitrite-user-0.0.1-SNAPSHOT.jar
    volumes:
      - /opt/web/amphitrite/user:/opt
    expose:
      - "8001"
    ports:
      - "8001:8001"
    environment:
      TZ: Asia/Shanghai
    networks:
      - poseidon

networks:
  poseidon:
    external: true
