version: '2'

services:
  engine:
    image: 172.31.21.226/ideal/openjdk:8
    hostname: engine
    container_name: engine
    command: java -Dfile.encoding=utf-8 -jar /opt/amphitrite-engine-0.0.1-SNAPSHOT.jar
    restart: always
    volumes:
      - /opt/web/amphitrite/engine:/opt
    expose:
      - "8000"
    ports:
      - "8000:8000"
    environment:
      TZ: Asia/Shanghai
    networks:
      - poseidon

  ims:
    image: 172.31.21.226/ideal/openjdk:8
    hostname: ims
    container_name: ims
    command: java -Dfile.encoding=utf-8 -jar /opt/amphitrite-ims-0.0.1-SNAPSHOT.jar
    restart: always
    volumes:
      - /opt/web/amphitrite/ims:/opt
    expose:
      - "8001"
    ports:
      - "8001:8001"
    environment:
      TZ: Asia/Shanghai
    networks:
      - poseidon

networks:
  poseidon:
    external: true
