apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-jobservice-config
data:
  UI_SECRET: "fktYKYj7brO0pPEr"
  JOBSERVICE_SECRET: "CghjwfMMF2vMmVIq"
  SECRET_KEY: "43IY8SIa5nyFLz8p"
  MAX_JOB_WORKERS: "3"
  LOG_LEVEL: debug
  GODEBUG: netdns=cgo
  CONFIG_PATH: /etc/jobservice/app.conf
  config: |
    appname = jobservice
    runmode = dev
    [dev]
    httpport = 80
