version: '2'

services:

  elasticsearch:
    build: elasticsearch/
    hostname: elasticsearch
    container_name: elasticsearch
    restart: always
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      TZ: Asia/Shanghai
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    networks:
      - elk
  # elasticsearch2:
  #   build: elasticsearch/
  #   hostname: elasticsearch2
  #   container_name: elasticsearch2
  #   volumes:
  #     - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  #     - esdata2:/usr/share/elasticsearch/data
  #   environment:
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - "discovery.zen.ping.unicast.hosts=elasticsearch"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   mem_limit: 1g
  #   networks:
  #     - elk

  logstash:
    build: logstash/
    hostname: logstash
    container_name: logstash
    restart: always
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
    environment:
      LS_JAVA_OPTS: -Xms256m -Xms256m
      TZ: Asia/Shanghai
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build: kibana/
    hostname: kibana
    container_name: kibana
    restart: always
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      TZ: Asia/Shanghai
    networks:
      - elk
    depends_on:
      - elasticsearch

volumes:
  esdata1:
    driver: local
  # esdata2:
  #   driver: local

networks:
  elk:
    driver: bridge
