version: '2'
services:
  mysql:
      image: mysql:8
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: paper
        MYSQL_ROOT_HOST: "%"
      expose:
        - "3306"

  weba:
      image: batizhao/alpine-openjdk:8
      command: java -jar opt/paper.jar
      volumes:
        - ./web/paper-0.0.1-SNAPSHOT.jar:/opt/paper.jar
      depends_on:
        - "mysql"
      links:
        - "mysql:database"
      expose:
        - "8080"
      environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/paper?useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=password
        - SPRING_DATASOURCE_SQL-SCRIPT-ENCODING=UTF-8

  webb:
      image: batizhao/alpine-openjdk:8
      command: java -jar opt/paper.jar
      volumes:
        - ./web/paper-0.0.1-SNAPSHOT.jar:/opt/paper.jar
      depends_on:
        - "mysql"
      links:
        - "mysql:database"
      expose:
        - "8080"
      environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/paper?useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=password
        - SPRING_DATASOURCE_SQL-SCRIPT-ENCODING=UTF-8

  haproxy:
      image: haproxy
      volumes:
        - ./haproxy:/haproxy-override
        - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      links:
        - weba
        - webb
      ports:
        - "80:80"
        - "70:70"
      expose:
        - "80"
        - "70"
