version: '2'
services:
  weba:
      build: ./web
      expose:
        - 8080

  webb:
      build: ./web
      expose:
        - 8080

  haproxy:
      image: haproxy:latest
      volumes:
          - ./haproxy:/haproxy-override
          - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      links:
          - weba
          - webb
      ports:
          - "80:80"
          - "70:70"
      expose:
          - "80"
          - "70"
