apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elk-esdata
  labels:
    k8s-app: elk-esdata
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
