apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-esdata
  labels:
    k8s-app: elk-esdata
  namespace: kube-system
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/elasticsearch
