apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  labels:
    task: logging
    k8s-app: logging-elasticsearch
  namespace: kube-system
data:
    elasticsearch.yml: |
      cluster.name: "es-docker-cluster"
      network.host: 0.0.0.0
      bootstrap.memory_lock: true
      discovery.zen.minimum_master_nodes: 1
      discovery.type: single-node
      xpack.ml.enabled: false
      xpack.monitoring.enabled: false
      xpack.security.enabled: false
      xpack.watcher.enabled: false
