apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-esdata
  labels:
    k8s-app: elk-esdata
  namespace: kube-system
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "k8s-volume"
    readOnly: false
